const WORDS = [
  "able", "above", "absorb", "accent", "accept", "access", "ace", "acid",
  "acorn", "act", "action", "active", "actual", "adapt", "add", "adjust",
  "admire", "admit", "adopt", "advice", "afford", "after", "again", "age",
  "agree", "ahead", "aid", "aide", "aim", "air", "airy", "alarm",
  "album", "alert", "algae", "alien", "align", "alive", "allow", "alloy",
  "along", "also", "alter", "among", "ample", "anchor", "angel", "angle",
  "angry", "ankle", "annoy", "annual", "answer", "ant", "anyone", "apart",
  "ape", "appeal", "apple", "apply", "arc", "area", "arena", "arise",
  "ark", "arm", "armor", "army", "aroma", "arrow", "art", "artist",
  "ash", "aside", "asked", "asking", "asset", "ate", "atlas", "attach",
  "attack", "attend", "attic", "audio", "audit", "author", "auto", "avail",
  "avoid", "awake", "award", "aware", "axe", "axis", "back", "backup",
  "bacon", "bad", "badge", "bag", "bake", "baker", "ball", "ballet",
  "bamboo", "ban", "banana", "band", "bank", "banner", "bar", "barn",
  "base", "basin", "basis", "basket", "bass", "bat", "batch", "bath",
  "battle", "bay", "beach", "beacon", "bead", "beam", "bear", "beard",
  "beat", "beauty", "bed", "before", "began", "begin", "behind", "being",
  "bell", "belong", "below", "belt", "bench", "bend", "berry", "beside",
  "best", "bet", "better", "beyond", "bid", "big", "bike", "bill",
  "bin", "bind", "bird", "bit", "bite", "bitter", "blank", "blanks",
  "blast", "blaze", "blazer", "bleed", "blend", "bless", "blind", "blink",
  "bliss", "block", "blond", "blonde", "bloom", "blow", "blown", "blue",
  "blur", "board", "boards", "boat", "boil", "bold", "bolt", "bond",
  "bone", "bonus", "book", "boom", "boot", "border", "born", "boss",
  "both", "bottle", "bounce", "bound", "bounty", "bow", "bowl", "box",
  "boy", "brace", "braid", "brain", "branch", "brand", "brass", "brave",
  "bread", "break", "bred", "breed", "breeze", "brew", "brick", "bridge",
  "brief", "bring", "broad", "broke", "bronze", "brook", "brown", "browse",
  "brush", "bubble", "buck", "bucket", "bud", "bug", "build", "built",
  "bulk", "bulky", "bumble", "bump", "bun", "bunch", "bunny", "burger",
  "burn", "burner", "burp", "burst", "bus", "bust", "butter", "button",
  "buy", "buyer", "buzz", "cab", "cabin", "cable", "cactus", "cafe",
  "cage", "cake", "call", "calm", "calmer", "came", "camel", "camera",
  "camp", "cancel", "candle", "candy", "cane", "canyon", "cap", "car",
  "card", "care", "cargo", "caring", "carpet", "carry", "cart", "carve",
  "case", "cash", "cast", "castle", "cat", "catch", "caught", "cause",
  "cave", "cedar", "celery", "cellar", "center", "chain", "chair", "chalk",
  "champ", "change", "chaos", "charge", "charm", "chart", "chase", "chat",
  "cheap", "cheat", "check", "cheek", "cheer", "chef", "cherry", "chess",
  "chest", "chief", "child", "chill", "chin", "chip", "chop", "chord",
  "chose", "chosen", "chunk", "church", "churn", "cider", "cigar", "circle",
  "city", "clad", "claim", "claims", "clam", "clamp", "clan", "clang",
  "clank", "clap", "clasp", "classy", "clay", "clean", "clear", "clerk",
  "clever", "click", "client", "cliff", "climb", "cling", "clip", "clock",
  "clod", "clog", "clone", "close", "closer", "cloth", "cloud", "clouds",
  "clown", "club", "clue", "clump", "coach", "coal", "coast", "coat",
  "coated", "cobalt", "cocoa", "code", "coffee", "coil", "coin", "cold",
  "collar", "color", "colt", "column", "comb", "come", "comet", "comic",
  "comics", "coming", "common", "comply", "cook", "cookie", "cool", "cop",
  "cope", "copper", "coral", "cord", "core", "cork", "corn", "corner",
  "cost", "cosy", "cotton", "couch", "could", "count", "county", "couple",
  "course", "court", "cover", "covers", "cow", "cozy", "crack", "craft",
  "crane", "crash", "crate", "crawl", "crayon", "craze", "crazy", "cream",
  "create", "credit", "creep", "crest", "crew", "crisp", "crop", "cross",
  "crow", "crowd", "crown", "cub", "cube", "cup", "curl", "curve",
  "custom", "cut", "cute", "cycle", "dab", "dad", "daily", "dairy",
  "dale", "dam", "damage", "dame", "damp", "dance", "dare", "daring",
  "dark", "dart", "dash", "data", "date", "dawn", "day", "deal",
  "dealer", "debug", "decade", "decent", "deck", "decoy", "deed", "deep",
  "defend", "degree", "delay", "delete", "demand", "den", "dense", "deny",
  "deploy", "depot", "depth", "derby", "design", "desire", "desk", "detail",
  "device", "dial", "dialog", "diary", "dice", "diet", "dig", "digit",
  "dim", "dine", "diner", "dinner", "dip", "direct", "dirt", "disc",
  "disco", "dish", "disk", "ditch", "divide", "dock", "dodge", "does",
  "dog", "domain", "dome", "donate", "done", "donkey", "donor", "door",
  "dose", "dot", "double", "down", "dozens", "draft", "drag", "drain",
  "drama", "drape", "draw", "drawer", "drawn", "dream", "dreams", "dress",
  "drew", "drill", "drink", "drip", "drive", "driver", "drop", "drum",
  "dry", "dryer", "dub", "duck", "duct", "due", "duel", "duet",
  "dug", "duke", "dull", "dump", "dune", "dunk", "duo", "dust",
  "dusty", "duty", "each", "eager", "eagle", "ear", "earn", "earth",
  "ease", "east", "easy", "eat", "eater", "edge", "edit", "editor",
  "effort", "egg", "ego", "elbow", "elder", "elite", "elk", "elm",
  "email", "ember", "emerge", "empire", "empty", "emu", "enable", "end",
  "ending", "enemy", "energy", "engage", "engine", "enjoy", "ensure", "enter",
  "entire", "equal", "equip", "era", "escape", "essay", "eve", "even",
  "event", "ever", "every", "exact", "exam", "exist", "expand", "expect",
  "expert", "extend", "extent", "extra", "eye", "fable", "fabric", "face",
  "fact", "factor", "fade", "fail", "fair", "fairly", "fairy", "faith",
  "fake", "fall", "false", "fame", "family", "famous", "fan", "fancy",
  "fang", "far", "farm", "farmer", "fast", "faster", "fat", "fate",
  "favor", "fawn", "fax", "fear", "feast", "fed", "fee", "feed",
  "feel", "feline", "fell", "felt", "fend", "fern", "fest", "few",
  "fiber", "fiddle", "field", "fifty", "fig", "file", "fill", "film",
  "filter", "fin", "final", "find", "fine", "finger", "finish", "fir",
  "fire", "firm", "fish", "fisher", "fist", "fit", "five", "fix",
  "flag", "flame", "flan", "flap", "flash", "flask", "flat", "flavor",
  "flaw", "flea", "fled", "flee", "flex", "flip", "float", "flock",
  "flog", "floor", "flora", "floss", "flow", "flower", "flue", "fluid",
  "fluke", "flush", "flute", "flux", "fly", "foam", "focal", "focus",
  "fog", "foil", "fold", "folder", "folk", "fond", "food", "fool",
  "foot", "force", "ford", "fore", "forest", "forge", "fork", "form",
  "format", "former", "fort", "forth", "found", "four", "fox", "frame",
  "frank", "free", "freeze", "fresh", "friend", "frog", "from", "front",
  "frost", "frozen", "fruit", "fry", "fuel", "full", "fully", "fume",
  "fun", "fund", "funnel", "fur", "fuse", "fusion", "fuss", "fuzz",
  "gag", "gain", "gait", "gal", "galaxy", "gale", "game", "gang",
  "gap", "garden", "gas", "gash", "gate", "gather", "gave", "gavel",
  "gaze", "gear", "gel", "gem", "gentle", "get", "giant", "gift",
  "gifted", "gig", "gild", "gilt", "gin", "gist", "give", "given",
  "giving", "glad", "glare", "glass", "gleam", "glee", "glen", "glib",
  "glide", "glob", "global", "globe", "gloss", "glove", "glow", "glue",
  "goals", "goat", "goes", "going", "gold", "golden", "golf", "gone",
  "good", "goof", "got", "govern", "gown", "grab", "grace", "grade",
  "grain", "grand", "grant", "grape", "grasp", "grass", "grassy", "grave",
  "gravel", "gravy", "gray", "green", "greet", "grew", "grid", "grill",
  "grin", "grind", "grip", "groom", "gross", "group", "grove", "grow",
  "grown", "growth", "guard", "guess", "guest", "guide", "guided", "guitar",
  "gulf", "gum", "gush", "gut", "guy", "gym", "habit", "hail",
  "hair", "half", "hall", "halt", "ham", "hammer", "hand", "handle",
  "hang", "happen", "happy", "harbor", "hard", "hare", "harm", "harp",
  "hash", "hasty", "hat", "haul", "have", "haven", "hay", "hazard",
  "haze", "hazel", "head", "heal", "healer", "heap", "heard", "heart",
  "hearth", "heat", "heaven", "heavy", "hedge", "heed", "heel", "hefty",
  "held", "hello", "helmet", "help", "hem", "hemp", "hen", "herb",
  "herd", "here", "hero", "hers", "hid", "hidden", "hide", "hike",
  "hiking", "hill", "hilt", "him", "hint", "hip", "hire", "hit",
  "hobby", "hockey", "hog", "hold", "holder", "hole", "hollow", "home",
  "honest", "honey", "honor", "hood", "hook", "hop", "hope", "hoping",
  "horn", "horse", "hose", "host", "hot", "hotel", "hour", "house",
  "hover", "hub", "hue", "hug", "huge", "hull", "hum", "human",
  "humor", "hump", "hung", "hunger", "hunt", "hunter", "hurt", "husk",
  "hut", "ice", "icy", "idea", "ideal", "ideals", "ignite", "ill",
  "image", "images", "imp", "impact", "inbox", "inch", "income", "indeed",
  "index", "indie", "indoor", "infant", "infer", "info", "inform", "ink",
  "inn", "inner", "input", "inside", "intend", "into", "invent", "invest",
  "invite", "ion", "iron", "island", "isle", "item", "ivory", "ivy",
  "jack", "jade", "jag", "jam", "jar", "jaw", "jay", "jazz",
  "jeep", "jelly", "jersey", "jest", "jet", "jewel", "jig", "jigsaw",
  "job", "jockey", "jog", "joins", "joint", "joke", "jolly", "jot",
  "joy", "jug", "juice", "jumble", "jumbo", "jump", "jumper", "jumpy",
  "junior", "jury", "just", "keen", "keep", "keg", "kelp", "ken",
  "kept", "kettle", "key", "kick", "kid", "kin", "kind", "kindle",
  "king", "kiss", "kit", "kite", "kitten", "lab", "label", "labor",
  "lace", "lack", "lad", "ladder", "lag", "laid", "lake", "lame",
  "lamp", "lance", "land", "landed", "lane", "lap", "lard", "large",
  "laser", "last", "late", "later", "laugh", "launch", "law", "lawn",
  "lawyer", "lay", "layer", "layout", "lazy", "lead", "leader", "leaf",
  "leak", "leaky", "lean", "leap", "learn", "lease", "leave", "led",
  "left", "leg", "legacy", "legal", "lemon", "lend", "lender", "lens",
  "less", "lesson", "let", "level", "lever", "lick", "lid", "life",
  "lift", "like", "limb", "lime", "limit", "limits", "limp", "line",
  "linen", "liner", "lining", "link", "lint", "lion", "lip", "liquid",
  "list", "listen", "lit", "live", "lively", "liver", "load", "loaf",
  "loan", "lobby", "local", "lock", "locker", "locket", "lodge", "loft",
  "log", "logic", "login", "logo", "lone", "long", "look", "loop",
  "loose", "lore", "lose", "loss", "lost", "lot", "lotus", "loud",
  "love", "lover", "low", "lower", "loyal", "luck", "lucky", "lump",
  "lunar", "lunch", "lung", "lyric", "mad", "made", "magnet", "maiden",
  "main", "make", "maker", "making", "manage", "manner", "manor", "manual",
  "many", "map", "maple", "mar", "marble", "march", "mare", "mark",
  "market", "marsh", "mash", "mask", "mason", "mass", "mast", "master",
  "mat", "match", "mate", "matter", "max", "mayor", "maze", "meal",
  "mean", "meats", "medal", "media", "medium", "melody", "melon", "member",
  "memo", "memory", "men", "mend", "mental", "mentor", "menu", "mercy",
  "mere", "merge", "merit", "merry", "mesh", "mess", "met", "metal",
  "meter", "method", "mid", "middle", "midst", "mild", "mile", "milk",
  "mill", "mime", "mind", "mine", "mining", "minor", "mint", "minus",
  "minute", "mirror", "miss", "mist", "mix", "mob", "mobile", "mock",
  "mode", "model", "modest", "mold", "mole", "molt", "moment", "money",
  "month", "mood", "moon", "mop", "moral", "more", "morn", "moss",
  "most", "mostly", "motel", "motive", "motor", "motto", "mound", "mount",
  "mouse", "mouth", "move", "movie", "moving", "much", "mud", "muddy",
  "mug", "mule", "mum", "mural", "museum", "music", "must", "muster",
  "mutual", "naive", "name", "nap", "napkin", "narrow", "nation", "nature",
  "naval", "navy", "near", "nearby", "neat", "neatly", "neck", "need",
  "nerves", "nest", "net", "new", "nice", "nil", "nimble", "nine",
  "nip", "noble", "nobody", "nod", "node", "noise", "none", "noon",
  "norm", "normal", "north", "nose", "note", "notice", "noun", "novel",
  "now", "number", "nun", "nurse", "nut", "nutty", "nylon", "oak",
  "oasis", "oat", "object", "obtain", "occupy", "occur", "ocean", "odd",
  "ode", "off", "offer", "oil", "old", "olive", "once", "one",
  "only", "onset", "onto", "ooze", "open", "opera", "opt", "optic",
  "option", "orange", "orb", "orbit", "organ", "origin", "other", "otter",
  "ours", "out", "outer", "outfit", "output", "oval", "oven", "over",
  "owe", "owl", "own", "owner", "oxygen", "pace", "pack", "pad",
  "paddle", "page", "pager", "paid", "pain", "paint", "pair", "pal",
  "palace", "palm", "pan", "panel", "panels", "pant", "paper", "par",
  "parent", "park", "parrot", "parse", "part", "partly", "party", "pass",
  "past", "paste", "pat", "patch", "path", "patter", "pause", "pave",
  "paw", "pay", "paying", "pea", "peak", "pearl", "peat", "pebble",
  "pedal", "peel", "peer", "peg", "pen", "pencil", "penny", "people",
  "pepper", "per", "perch", "period", "permit", "pest", "pet", "pick",
  "picked", "pickle", "picnic", "pie", "piece", "pier", "pig", "pile",
  "pillow", "pilot", "pin", "pinch", "pine", "pink", "pipe", "pirate",
  "piston", "pit", "pitch", "pixel", "place", "plain", "plan", "planet",
  "plant", "plate", "play", "player", "plaza", "plea", "please", "pledge",
  "plenty", "pliers", "plot", "plow", "pluck", "plug", "plum", "plumb",
  "plump", "plus", "pocket", "pod", "poem", "poet", "poetry", "points",
  "poke", "polar", "polish", "polls", "polo", "pond", "pool", "poor",
  "pop", "pope", "porch", "pore", "pork", "port", "portal", "pose",
  "post", "poster", "pot", "pound", "pour", "pow", "powder", "power",
  "prefer", "prep", "press", "pretty", "price", "pride", "prime", "print",
  "prior", "prize", "pro", "probe", "profit", "prompt", "prone", "proof",
  "prop", "prose", "proud", "proven", "pub", "public", "pug", "pull",
  "pulp", "pump", "pun", "punk", "pup", "pure", "pursue", "push",
  "put", "puzzle", "quiz", "rabbit", "race", "racing", "rack", "radish",
  "raft", "rag", "rage", "raid", "rail", "rain", "rake", "ram",
  "ramp", "ran", "random", "rang", "rank", "rap", "rare", "rat",
  "rate", "ray", "reader", "real", "really", "ream", "rear", "reason",
  "recall", "recent", "record", "red", "reduce", "ref", "reform", "region",
  "reject", "rely", "remain", "remote", "remove", "rent", "rental", "repeat",
  "report", "rescue", "resort", "rest", "result", "retail", "retire", "reveal",
  "review", "reward", "rib", "ribbon", "rice", "rich", "rid", "riddle",
  "ride", "rift", "rig", "rim", "rind", "ring", "riot", "rip",
  "rise", "risk", "road", "roam", "roar", "rob", "robe", "rock",
  "rocket", "rod", "rode", "roll", "roller", "roof", "room", "root",
  "rope", "rose", "rosy", "rot", "row", "rub", "rug", "rule",
  "ruling", "rum", "run", "runner", "rush", "rust", "rustic", "sad",
  "saddle", "safe", "safely", "sag", "sage", "said", "sailor", "sake",
  "salary", "salt", "same", "sample", "sand", "sane", "sang", "sap",
  "sash", "sat", "save", "saw", "say", "scan", "scenic", "season",
  "second", "secret", "seed", "seeing", "seek", "select", "self", "sell",
  "seller", "send", "senior", "series", "set", "settle", "severe", "sew",
  "shadow", "shield", "ship", "shop", "show", "shy", "sick", "side",
  "sign", "signal", "silk", "sill", "silver", "simple", "sing", "singer",
  "single", "sink", "sip", "sir", "sis", "sit", "six", "size",
  "sketch", "ski", "skills", "skim", "skip", "sky", "slam", "sleeve",
  "slip", "slow", "slower", "smooth", "snap", "snow", "soak", "soap",
  "social", "sofa", "soft", "softer", "soil", "sold", "sole", "solved",
  "some", "song", "soon", "sort", "soup", "source", "soy", "spa",
  "speech", "spin", "spit", "splash", "spoken", "spot", "spring", "spry",
  "square", "stable", "stairs", "star", "status", "stay", "steady", "stem",
  "step", "stereo", "stew", "stir", "stitch", "stocks", "stop", "strand",
  "street", "string", "stripe", "strong", "struck", "studio", "sub", "subtle",
  "such", "sudden", "sue", "suit", "sum", "summer", "summit", "sun",
  "sung", "sunset", "superb", "supply", "sure", "surely", "surf", "survey",
  "swap", "swim", "switch", "symbol", "system", "tab", "tack", "tackle",
  "tad", "tag", "tail", "take", "taking", "talent", "talk", "tall",
  "tame", "tan", "tank", "tap", "tape", "tar", "target", "task",
  "tat", "tax", "taxi", "team", "tear", "tell", "temp", "temple",
  "ten", "tend", "tender", "tennis", "tent", "term", "test", "text",
  "than", "that", "them", "then", "thin", "this", "thread", "throne",
  "tick", "tide", "tidy", "tie", "tied", "tier", "tile", "till",
  "tilt", "timber", "time", "tin", "tiny", "tip", "tire", "tissue",
  "toad", "toe", "toggle", "toil", "told", "toll", "ton", "tone",
  "took", "tool", "top", "tore", "torn", "tot", "tour", "tow",
  "toward", "town", "toy", "tracks", "trails", "trap", "travel", "tray",
  "tree", "trek", "trends", "trim", "trio", "trip", "triple", "trucks",
  "true", "try", "tub", "tube", "tuck", "tug", "tune", "tunnel",
  "turf", "turn", "turtle", "tusk", "twin", "two", "type", "undo",
  "unique", "unit", "united", "unless", "update", "upon", "urge", "urn",
  "use", "used", "useful", "user", "valley", "van", "vane", "vary",
  "vase", "vat", "veil", "vendor", "vent", "verb", "very", "vessel",
  "vest", "vet", "vie", "view", "viewer", "vine", "violet", "vision",
  "visual", "volume", "vote", "wade", "wag", "wage", "wait", "wake",
  "walk", "wall", "wand", "ward", "warm", "warmth", "warn", "wash",
  "wave", "wavy", "wax", "way", "wealth", "wear", "web", "wed",
  "weed", "week", "weekly", "weld", "well", "went", "were", "west",
  "wet", "what", "wheels", "when", "wide", "wife", "wig", "wild",
  "wildly", "will", "win", "wind", "window", "wine", "wing", "wink",
  "winner", "winter", "wipe", "wire", "wisdom", "wise", "wish", "wit",
  "with", "wok", "wolf", "wonder", "wood", "wool", "word", "wore",
  "work", "worthy", "yak", "yam", "yap", "yard", "yaw", "year",
  "yell", "yellow", "yen", "yes", "yoga", "yoke", "you", "your",
  "zap", "zen", "zenith", "zig", "zip", "zone", "zoo", "zoom"
];

// Make it available for validation
export const WORD_SET = new Set(WORDS);

/**
 * Generate a 2-word codename using cryptographically secure randomness.
 * @returns {string} e.g. "bold-echo"
 */
export function generateCodename() {
  const indices = new Uint32Array(2);
  crypto.getRandomValues(indices);
  return Array.from(indices)
    .map(n => WORDS[n % WORDS.length])
    .join("-");
}

/**
 * Generate a 4-word room code using cryptographically secure randomness.
 * @returns {string} e.g. "alpine-breeze-crystal-drift"
 */
export function generateRoomCode() {
  const indices = new Uint32Array(4);
  crypto.getRandomValues(indices);
  return Array.from(indices)
    .map(n => WORDS[n % WORDS.length])
    .join("-");
}

/**
 * Check if input is a valid 4-word room code (all words in the word list).
 * @param {string} input - hyphenated room code
 * @returns {boolean}
 */
export function isValidRoomCode(input) {
  if (typeof input !== "string") return false;
  const parts = input.split("-");
  return parts.length === 4 && parts.every(w => WORD_SET.has(w));
}

/**
 * Normalize user input into hyphenated room code format.
 * Accepts spaces or hyphens as separators, lowercases everything.
 * @param {string} input
 * @returns {string|null} normalized hyphenated code, or null if invalid
 */
export function normalizeRoomCode(input) {
  if (typeof input !== "string") return null;
  const normalized = input.trim().toLowerCase().replace(/[\s-]+/g, "-");
  return isValidRoomCode(normalized) ? normalized : null;
}
